

%Define the observation and action expectations for the agent
observations = rlNumericSpec([10 1], ...
    'LowerLimit', [zeros(5,1); zeros(5,1)], ...
    'UpperLimit', [1600*ones(5,1); pi*ones(5,1)], ...
    'Name', 'NodeDistancesAndAngles');


actions = rlNumericSpec([10 1], ...
    'LowerLimit', [zeros(5,1); zeros(5,1)], ...
    'UpperLimit', [ones(5,1); 2*pi*ones(5,1)], ...
    'Name', 'AmplitudePhase');

env = rlFunctionEnv(observations,actions,"myStep","myReset");

%reset(env)
%step(env, rand(10,1))   % Random test action